### ISSUE TITLE
Merge conflict lines committed into source

### ISSUE THREAD

**Issue by mdavis777** [microsoft/ElectionGuard-SDK-C-Implementation#1]
Commit 0b30d4044d69606925f1e748517f0ca410cc0f44 added merge commit lines in 
[ examples/simple/CMakeLists.txt](https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/commit/0b30d4044d69606925f1e748517f0ca410cc0f44#diff-aa9b5a8d7c967b0fcf51a2fb20cbfe25) and [src/electionguard/sha2-openbsd.h ](https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/commit/0b30d4044d69606925f1e748517f0ca410cc0f44#diff-4111e5625bdbdc70c94ef832a1690b8e)

**Comment by supr** [comment]
https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/compare/master...supr:fix_build?expand=1 incase some one needs it
