### ISSUE TITLE
When I followed your steps to compile in windows, I couldn't find the vendor-sdk folder. What is going on? Thanks

### ISSUE THREAD

**Issue by flamelu** [microsoft/ElectionGuard-SDK-C-Implementation#45]
## Generic Issue

- [ ] Ensure this issue is not a bug report or feature request

**Description**
A clear and concise description of the issue.

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by echumley-msft** [comment]
Thanks for flagging, due to an old naming convention. Updated in PR #50 with proper name
