### ISSUE TITLE
pow_mod_q TRACE_PRINT is incorrect

### ISSUE THREAD

**Issue by weaversa** [microsoft/ElectionGuard-SDK-C-Implementation#87]
## Bug Report

**Current Behavior**
`pow_mod_q` uses `p` rather than `q` in two places. Clearly a copy/paste error.

**Expected behavior/code**
```
void pow_mod_q(mpz_t res, const mpz_t base, const mpz_t exp)
{
    mpz_powm(res, base, exp, q);

    TRACE_PRINT(("Performing operation powmod (base^exp)%%p"));
    TRACE_PRINT(("\nbase = "));
    print_base16(base);
    TRACE_PRINT(("\nexp = "));
    print_base16(exp);
    TRACE_PRINT(("\np = "));
    print_base16(p);
    TRACE_PRINT(("\nresult = "));
    print_base16(res);
    TRACE_PRINT(("\n"));
}
```
Should be
```
void pow_mod_q(mpz_t res, const mpz_t base, const mpz_t exp)
{
    mpz_powm(res, base, exp, q);

    TRACE_PRINT(("Performing operation powmod (base^exp)%%q"));
    TRACE_PRINT(("\nbase = "));
    print_base16(base);
    TRACE_PRINT(("\nexp = "));
    print_base16(exp);
    TRACE_PRINT(("\np = "));
    print_base16(q);
    TRACE_PRINT(("\nresult = "));
    print_base16(res);
    TRACE_PRINT(("\n"));
}
```

**Comment by echumley-msft** [comment]
Hi, thanks for raising this issue - we've recently transitioned the primary ElectionGuard reference implementation to the [ElectionGuard-Python](https://github.com/microsoft/electionguard-python) repository. The team believes this issue has been resolved or mitigated there, so closing this issue for now as this repository will no longer be actively maintained. Please feel free to check and leave comments in the latest [repo](https://github.com/microsoft/electionguard-python).
