### ISSUE TITLE
Suspect if statement

### ISSUE THREAD

**Issue by weaversa** [microsoft/ElectionGuard-SDK-C-Implementation#88]
https://github.com/microsoft/electionguard-c/blob/2d9d55d2aea6302396ece6414516514998866c83/src/electionguard/bignum.c#L179-L181

The tabbing of these lines seems weird. Here they are in context.

https://github.com/microsoft/electionguard-c/blob/2d9d55d2aea6302396ece6414516514998866c83/src/electionguard/bignum.c#L172-L182

You'll also notice that the `while` loop does not modify either `a` or `max_decryption`, making these lines of code even more suspect.

**Comment by jldodds** [comment]
Thanks @weaversa! It should definitely be ```result``` in that comparison, not ```a```. The result is that this loop will ignore the max_decryption. This isn't a huge correctness bug, but the function will loop (functionally) forever if something goes wrong with the encrypted value it receives.

**Comment by echumley-msft** [comment]
Hi, thanks for raising this issue - we've recently transitioned the primary ElectionGuard reference implementation to the [ElectionGuard-Python](https://github.com/microsoft/electionguard-python) repository. The team believes this issue has been resolved or mitigated there, so closing this issue for now as this repository will no longer be actively maintained. Please feel free to check and leave comments in the latest [repo](https://github.com/microsoft/electionguard-python).
